spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zee5appProd
    username: root
    password: Pass@123
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.zee.zee5app.utils.CustomTableNameStrategy
    show-sql: true
server:
  port: 9005

zee5app:
  app:
    jwtSecret: secretkey
    jwtExpirationMs: 86400000